" -----> Windows .vimrc file <-----
set nocompatible              " be iMproved, required

" set the runtime path to include Vundle and initialize
set rtp+=$HOME/.vim/bundle/Vundle.vim/
call vundle#begin('$HOME/.vim/bundle/')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'haishanh/night-owl.vim'
Plugin 'challenger-deep-theme/vim', {'name': 'challenger-deep-theme'}
Plugin 'dracula/vim', { 'name': 'dracula' }
Plugin 'chriskempson/base16-vim'
Plugin 'tpope/vim-fugitive'
Plugin 'itchyny/lightline.vim'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'jiangmiao/auto-pairs'
Plugin 'pseewald/vim-anyfold'
Plugin 'tpope/vim-vinegar'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-speeddating'
Plugin 'mattn/emmet-vim'
Plugin 'airblade/vim-gitgutter'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
colorscheme dracula
set guifont=Consolas:h13:cANSI:qDRAFT
"set guifont=inconsolata:h13:cANSI:qDRAFT
set number
set norelativenumber
set fileencodings=utf-8
set fileencoding=utf-8
set tabstop=4
set shiftwidth=4
set expandtab
set foldmethod=indent
set nobackup
set noundofile
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_browse_split = 2
let g:netrw_winsize = 30
map <C-S-Left> :Vexplore <CR>
map <C-S-Down> :Hexplore <CR>

" -----> Terminal GUI Colors Configuration <-----
if has('nvim') || has('termguicolors')
  set termguicolors
endif

" -----> GUI True Colors Configuration <-----
set laststatus=2
if !has('gui_running')
  set t_Co=256
endif

set noshowmode  " to get rid of thing like --INSERT--
set noshowcmd  " to get rid of display of last command
set shortmess+=F  " to get rid of the file name displayed in the command line bar
let g:lightline = {
      \ 'colorscheme': 'challenger_deep',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

" ----->Anyfold Configuration<-----
autocmd Filetype * AnyFoldActivate
let g:anyfold_fold_comments=1
set foldlevel=99

" ----->Gitgutter Configuration<-----
let g:gitgutter_git_executable = 'C:\software\Git\bin\git.exe'
let g:gitgutter_max_signs = 750
set updatetime=100

" ----->Emmet Configuration<-----
"let g:user_emmet_mode='n'    "only enable normal mode functions.
"let g:user_emmet_mode='inv'  "enable all functions, which is equal to
let g:user_emmet_mode='a'    "enable all function in all mode.
